### ISSUE TITLE
Problem with base on Formbot v2 350 - Bed is higher

### ISSUE THREAD

**Issue by AMFkuna** [Dendrowen/Blobifier#6]
I have a problem with the base on my 350. Even if I move the bed as far to the right as possible, it still interferes with proper bed placement.

![IMG_6140](https://github.com/Dendrowen/Blobifier/assets/17743216/daf369a5-750d-480c-8df3-63fd2073d749)

**Comment by AMFkuna** [comment]
I had to cut off the base to make it fit.
![IMG_6141](https://github.com/Dendrowen/Blobifier/assets/17743216/449bc526-caa9-4ce5-974f-635cc4110cc1)
![IMG_6142](https://github.com/Dendrowen/Blobifier/assets/17743216/5be89f76-9eb3-4cba-a31a-3e80e250c03a)

**Comment by Dendrowen** [comment]
What is the width of your bed?

**Comment by AMFkuna** [comment]
355

**Comment by Dendrowen** [comment]
I have added a new mount for the slightly wider beds. (My bed is 300mm) 
This should solve the 2.5mm misalignment. You can find it in the beta branch. Do you want to test this and report back?

**Comment by AMFkuna** [comment]
Mount does not solve this, it also shifts the bucket switch and creates a gap between bucket and base.

**Comment by Dendrowen** [comment]
Oh, right. In that case I'll leave this open for now while I'll think of a pretty solution.

Thanks for testing!

**Comment by Dendrowen** [comment]
Included wider buckets
